# Generated by Django 4.1.7 on 2023-03-29 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_portfolio_balance_alter_coin_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='username',
        ),
        migrations.AlterField(
            model_name='coin',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.coin')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(through='login.Transaction', to='login.coin'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.userprofile'),
        ),
    ]
