# Generated by Django 4.1.7 on 2023-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_coin_description_remove_coin_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=16),
        ),
    ]
