# Generated by Django 4.1.7 on 2023-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='current_price',
        ),
        migrations.AddField(
            model_name='coin',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='coin',
            name='last_updated',
            field=models.DateTimeField(default='2022-03-02'),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
