# Generated by Django 4.1.7 on 2023-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_coin_current_price_coin_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='last_updated',
            field=models.DateTimeField(default='2022-03-02'),
        ),
    ]
