# Generated by Django 4.1.7 on 2023-03-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_coin_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
